/**
 * Seed content for the cookbook.
 *
 * Coverage is deliberate: every meal type appears at every time bucket that
 * makes sense for it, so filters in T6/T10 always have something to return.
 * Quick <= 15 min, Average 16-40, Commitment > 40.
 */

/** Ingredients that are assumed in stock and hidden from missing-ingredient counts. */
export const STAPLES = [
  "salt",
  "black pepper",
  "olive oil",
  "butter",
  "plain flour",
  "caster sugar",
  "water",
];

/** name -> category. Categories drive sidebar grouping and cart aisle order. */
export const INGREDIENT_CATEGORIES = {
  // staples — categorised like anything else so they group correctly when shown
  salt: "spice",
  "black pepper": "spice",
  "olive oil": "pantry",
  butter: "dairy",
  "plain flour": "pantry",
  "caster sugar": "pantry",
  water: "pantry",
  // produce
  garlic: "produce",
  onion: "produce",
  "red onion": "produce",
  "spring onion": "produce",
  tomato: "produce",
  "cherry tomatoes": "produce",
  "red pepper": "produce",
  "green pepper": "produce",
  "red chilli": "produce",
  lemon: "produce",
  lime: "produce",
  avocado: "produce",
  cucumber: "produce",
  carrot: "produce",
  celery: "produce",
  potato: "produce",
  mushrooms: "produce",
  courgette: "produce",
  spinach: "produce",
  "romaine lettuce": "produce",
  basil: "produce",
  "flat-leaf parsley": "produce",
  coriander: "produce",
  dill: "produce",
  thyme: "produce",
  ginger: "produce",
  banana: "produce",
  "mixed berries": "produce",
  "green beans": "produce",
  // protein
  eggs: "protein",
  "chicken breast": "protein",
  "whole chicken": "protein",
  "chicken thighs": "protein",
  "beef chuck": "protein",
  "streaky bacon": "protein",
  "pork sausages": "protein",
  "salmon fillet": "protein",
  "tinned tuna": "protein",
  chickpeas: "protein",
  "cannellini beans": "protein",
  // dairy
  milk: "dairy",
  "greek yogurt": "dairy",
  "double cream": "dairy",
  parmesan: "dairy",
  cheddar: "dairy",
  mozzarella: "dairy",
  feta: "dairy",
  // grain
  spaghetti: "grain",
  "arborio rice": "grain",
  "basmati rice": "grain",
  "rolled oats": "grain",
  "sourdough bread": "grain",
  "flour tortillas": "grain",
  "ditalini pasta": "grain",
  "popcorn kernels": "grain",
  // pantry
  "baking powder": "pantry",
  "bicarbonate of soda": "pantry",
  honey: "pantry",
  "maple syrup": "pantry",
  tahini: "pantry",
  "peanut butter": "pantry",
  walnuts: "pantry",
  almonds: "pantry",
  "desiccated coconut": "pantry",
  "chia seeds": "pantry",
  "dark chocolate": "pantry",
  "tinned tomatoes": "pantry",
  "tomato puree": "pantry",
  "coconut milk": "pantry",
  "chicken stock": "pantry",
  "vegetable stock": "pantry",
  "beef stock": "pantry",
  "red wine": "pantry",
  "white wine": "pantry",
  "dijon mustard": "pantry",
  mayonnaise: "pantry",
  "soy sauce": "pantry",
  "sesame oil": "pantry",
  "green curry paste": "pantry",
  "fish sauce": "pantry",
  "anchovy fillets": "pantry",
  "vegetable oil": "pantry",
  buttermilk: "pantry",
  "baked beans": "pantry",
  "sunflower seeds": "pantry",
  "pumpkin seeds": "pantry",
  "strong white flour": "pantry",
  "fast-action yeast": "pantry",
  rosemary: "produce",
  "sea salt flakes": "spice",
  // spice
  "ground cumin": "spice",
  "smoked paprika": "spice",
  "sweet paprika": "spice",
  "ground coriander": "spice",
  "cayenne pepper": "spice",
  "dried oregano": "spice",
  "bay leaf": "spice",
  "chilli flakes": "spice",
  "ground cinnamon": "spice",
  "vanilla extract": "spice",
  "curry powder": "spice",
};

/** Alternate names the T19 resolver should map onto a canonical ingredient. */
export const ALIASES = {
  "spring onion": ["scallion", "green onion", "scallions"],
  coriander: ["cilantro", "fresh coriander"],
  courgette: ["zucchini"],
  chickpeas: ["garbanzo beans", "garbanzos"],
  "plain flour": ["all-purpose flour", "ap flour"],
  "caster sugar": ["superfine sugar", "granulated sugar"],
  "double cream": ["heavy cream", "whipping cream"],
  "rolled oats": ["old-fashioned oats", "porridge oats"],
  "red pepper": ["red bell pepper", "red capsicum"],
  "green pepper": ["green bell pepper", "green capsicum"],
  "tinned tomatoes": ["canned tomatoes", "chopped tomatoes"],
  "tinned tuna": ["canned tuna"],
  "bicarbonate of soda": ["baking soda"],
  "flat-leaf parsley": ["italian parsley", "parsley"],
  "streaky bacon": ["bacon"],
  "romaine lettuce": ["cos lettuce"],
  "beef chuck": ["chuck steak", "stewing beef"],
  "strong white flour": ["bread flour"],
};

/**
 * i: [name, amount, unit, prep_note, optional]
 * Amount may be null for "to taste" style entries.
 */
export const RECIPES = [
  // ---------------------------------------------------------------- breakfast
  {
    title: "Greek Yogurt with Honey and Walnuts",
    description: "Three minutes, no cooking, and still feels deliberate rather than lazy.",
    meal_types: ["breakfast", "snack"],
    time_minutes: 5,
    servings: 1,
    i: [
      ["greek yogurt", 200, "g"],
      ["honey", 1, "tbsp"],
      ["walnuts", 20, "g", "roughly chopped"],
      ["mixed berries", 60, "g", null, true],
      ["ground cinnamon", null, "pinch", null, true],
    ],
    steps: [
      "Spoon the yogurt into a bowl and level the surface.",
      "Toast the walnuts in a dry pan for two minutes until they smell nutty, then chop.",
      "Drizzle over the honey, scatter the walnuts and berries, and dust with cinnamon.",
    ],
  },
  {
    title: "Overnight Oats",
    description: "Ten minutes tonight buys you a breakfast that needs nothing tomorrow.",
    meal_types: ["breakfast"],
    time_minutes: 10,
    servings: 2,
    i: [
      ["rolled oats", 100, "g"],
      ["milk", 250, "ml"],
      ["greek yogurt", 100, "g"],
      ["chia seeds", 2, "tbsp"],
      ["maple syrup", 1, "tbsp"],
      ["banana", 1, "", "sliced"],
      ["mixed berries", 80, "g", null, true],
    ],
    steps: [
      "Stir the oats, milk, yogurt, chia seeds and maple syrup together in a jar.",
      "Cover and refrigerate overnight, or at least four hours.",
      "Top with sliced banana and berries just before eating, so they don't go soft.",
    ],
  },
  {
    title: "Shakshuka",
    description: "Eggs poached in a spiced tomato base. One pan, and the bread does the rest.",
    meal_types: ["breakfast", "lunch"],
    time_minutes: 30,
    servings: 2,
    i: [
      ["olive oil", 2, "tbsp"],
      ["onion", 1, "", "finely sliced"],
      ["red pepper", 1, "", "sliced"],
      ["garlic", 3, "cloves", "sliced"],
      ["ground cumin", 1, "tsp"],
      ["sweet paprika", 1, "tsp"],
      ["cayenne pepper", null, "pinch"],
      ["tinned tomatoes", 400, "g"],
      ["eggs", 4, ""],
      ["feta", 60, "g", "crumbled", true],
      ["coriander", null, "handful", "chopped"],
      ["sourdough bread", 4, "slices"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Soften the onion and pepper in the oil over medium heat for eight minutes.",
      "Add the garlic and spices and cook for one minute, until fragrant.",
      "Tip in the tomatoes, season, and simmer for ten minutes until thickened.",
      "Make four wells, crack an egg into each, cover, and cook five minutes for runny yolks.",
      "Scatter with feta and coriander. Serve with bread for scooping.",
    ],
  },
  {
    title: "Buttermilk Pancakes",
    description: "The buttermilk is what makes them tall. Don't overmix.",
    meal_types: ["breakfast"],
    time_minutes: 25,
    servings: 4,
    i: [
      ["plain flour", 250, "g"],
      ["caster sugar", 2, "tbsp"],
      ["baking powder", 2, "tsp"],
      ["bicarbonate of soda", 1, "tsp"],
      ["salt", 0.5, "tsp"],
      ["buttermilk", 400, "ml"],
      ["eggs", 2, ""],
      ["butter", 50, "g", "melted"],
      ["maple syrup", null, "to serve"],
    ],
    steps: [
      "Whisk the dry ingredients together in a large bowl.",
      "Beat the buttermilk, eggs and melted butter in another bowl.",
      "Fold wet into dry until just combined — lumps are correct, a smooth batter is overmixed.",
      "Rest the batter ten minutes while the pan heats over medium-low.",
      "Cook in butter, roughly two minutes a side, flipping when bubbles hold their shape.",
    ],
  },
  {
    title: "Full English Breakfast",
    description: "Everything at once, hot at the same time. The timing is the whole skill.",
    meal_types: ["breakfast"],
    time_minutes: 45,
    servings: 2,
    i: [
      ["pork sausages", 4, ""],
      ["streaky bacon", 4, "rashers"],
      ["eggs", 2, ""],
      ["tomato", 2, "", "halved"],
      ["mushrooms", 150, "g", "halved"],
      ["baked beans", 200, "g"],
      ["sourdough bread", 2, "slices"],
      ["butter", 20, "g"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Start the sausages in a cold oven-safe pan over medium-low heat; they need twenty minutes.",
      "After ten minutes add the bacon, tomatoes cut-side down, and mushrooms.",
      "Warm the beans in a small pan. Toast and butter the bread.",
      "Fry the eggs last in the rendered fat, two minutes for a set white and runny yolk.",
      "Plate everything at once. Season the tomatoes and mushrooms, not the bacon.",
    ],
  },

  // -------------------------------------------------------------------- lunch
  {
    title: "Tuna Melt",
    description: "The good version: sharp cheddar, real mustard, and a properly hot pan.",
    meal_types: ["lunch"],
    time_minutes: 12,
    servings: 2,
    i: [
      ["tinned tuna", 160, "g", "drained"],
      ["mayonnaise", 3, "tbsp"],
      ["dijon mustard", 1, "tsp"],
      ["spring onion", 2, "", "finely sliced"],
      ["cheddar", 80, "g", "grated"],
      ["sourdough bread", 4, "slices"],
      ["butter", 30, "g", "softened"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Fork the tuna with the mayonnaise, mustard, spring onion and plenty of pepper.",
      "Butter the outsides of all four slices — that face goes in the pan.",
      "Build each sandwich with tuna and cheddar, buttered sides out.",
      "Cook over medium-low for four minutes a side, pressing gently, until the cheese runs.",
    ],
  },
  {
    title: "Caprese Sandwich",
    description: "Three good ingredients and nothing to hide behind.",
    meal_types: ["lunch", "snack"],
    time_minutes: 10,
    servings: 2,
    i: [
      ["sourdough bread", 4, "slices"],
      ["mozzarella", 150, "g", "torn"],
      ["tomato", 2, "", "thickly sliced"],
      ["basil", null, "handful"],
      ["olive oil", 2, "tbsp"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Salt the tomato slices and leave them five minutes, then pat dry.",
      "Drizzle the bread with olive oil.",
      "Layer mozzarella, tomato and basil; season and close.",
      "Press under something heavy for a few minutes if you have the patience.",
    ],
  },
  {
    title: "Egg Fried Rice",
    description: "Day-old rice is not a suggestion — fresh rice steams instead of frying.",
    meal_types: ["lunch", "dinner"],
    time_minutes: 15,
    servings: 2,
    i: [
      ["basmati rice", 300, "g", "cooked and chilled"],
      ["eggs", 3, "", "beaten"],
      ["spring onion", 3, "", "sliced"],
      ["garlic", 2, "cloves", "minced"],
      ["soy sauce", 2, "tbsp"],
      ["sesame oil", 1, "tsp"],
      ["vegetable oil", 2, "tbsp"],
      ["green beans", 100, "g", "trimmed", true],
    ],
    steps: [
      "Get the pan properly hot — hotter than feels sensible — before anything goes in.",
      "Scramble the eggs in half the oil until just set, then remove.",
      "Fry the garlic and white parts of the spring onion for thirty seconds.",
      "Add the rice and press it flat; leave it alone a minute at a time to catch.",
      "Return the egg, add soy and sesame oil, and finish with the green tops.",
    ],
  },
  {
    title: "Chicken Caesar Salad",
    description: "Anchovies in the dressing are not optional. You won't taste fish, only depth.",
    meal_types: ["lunch", "dinner"],
    time_minutes: 25,
    servings: 2,
    i: [
      ["chicken breast", 2, ""],
      ["romaine lettuce", 1, "head", "torn"],
      ["parmesan", 50, "g", "shaved"],
      ["sourdough bread", 2, "slices", "cubed"],
      ["anchovy fillets", 4, ""],
      ["garlic", 1, "clove"],
      ["dijon mustard", 1, "tsp"],
      ["mayonnaise", 4, "tbsp"],
      ["lemon", 0.5, "", "juiced"],
      ["olive oil", 3, "tbsp"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Toss the bread cubes in olive oil and bake at 200C for ten minutes until golden.",
      "Season the chicken and pan-fry six minutes a side; rest five minutes, then slice.",
      "Mash the anchovies and garlic to a paste, then whisk in mustard, mayonnaise and lemon.",
      "Toss the lettuce through the dressing, then add chicken, croutons and parmesan.",
    ],
  },
  {
    title: "Minestrone Soup",
    description: "A clear-out-the-drawer soup that improves on the second day.",
    meal_types: ["lunch", "dinner"],
    time_minutes: 50,
    servings: 4,
    i: [
      ["olive oil", 3, "tbsp"],
      ["onion", 1, "", "diced"],
      ["carrot", 2, "", "diced"],
      ["celery", 2, "sticks", "diced"],
      ["garlic", 3, "cloves", "minced"],
      ["courgette", 1, "", "diced"],
      ["tinned tomatoes", 400, "g"],
      ["vegetable stock", 1.2, "l"],
      ["cannellini beans", 400, "g", "drained"],
      ["ditalini pasta", 150, "g"],
      ["parmesan", 40, "g", "grated"],
      ["basil", null, "handful"],
      ["bay leaf", 1, ""],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Sweat onion, carrot and celery in the oil for twelve minutes — slowly, no colour.",
      "Add garlic and courgette, cook three minutes more.",
      "Add tomatoes, stock and bay leaf; simmer twenty minutes.",
      "Add beans and pasta and cook until the pasta is just done, about ten minutes.",
      "Season hard, and finish each bowl with parmesan and torn basil.",
    ],
  },

  // ------------------------------------------------------------------- dinner
  {
    title: "Spaghetti Aglio e Olio",
    description: "Five ingredients. The emulsion of pasta water and oil is the entire dish.",
    meal_types: ["dinner"],
    time_minutes: 15,
    servings: 2,
    i: [
      ["spaghetti", 200, "g"],
      ["garlic", 6, "cloves", "thinly sliced"],
      ["olive oil", 80, "ml"],
      ["chilli flakes", 1, "tsp"],
      ["flat-leaf parsley", null, "handful", "chopped"],
      ["parmesan", 40, "g", "grated", true],
      ["salt", null, "to taste"],
    ],
    steps: [
      "Boil the spaghetti in well-salted water, pulling it a minute before the packet says.",
      "Meanwhile warm the oil and garlic together from cold over low heat.",
      "When the garlic is pale gold — not brown — add the chilli flakes.",
      "Add the pasta plus a ladle of its water and toss hard for a minute until glossy.",
      "Off the heat, stir through the parsley.",
    ],
  },
  {
    title: "Salmon with Lemon and Dill",
    description: "Skin-side down and left alone. Most salmon is ruined by fiddling.",
    meal_types: ["dinner"],
    time_minutes: 20,
    servings: 2,
    i: [
      ["salmon fillet", 2, ""],
      ["lemon", 1, ""],
      ["dill", null, "small handful", "chopped"],
      ["butter", 30, "g"],
      ["olive oil", 1, "tbsp"],
      ["green beans", 200, "g", "trimmed"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Dry the skin thoroughly and salt it. Wet skin will not crisp.",
      "Lay the fillets skin-down in a cold oiled pan, then bring to medium-high.",
      "Cook six minutes without moving them, until the flesh is opaque two-thirds up.",
      "Flip for ninety seconds, add butter, dill and a squeeze of lemon, and baste.",
      "Steam the beans four minutes and dress with the pan butter.",
    ],
  },
  {
    title: "Chicken Fajitas",
    description: "High heat, don't crowd the pan, and char is the point.",
    meal_types: ["dinner"],
    time_minutes: 30,
    servings: 4,
    i: [
      ["chicken thighs", 600, "g", "sliced"],
      ["red pepper", 1, "", "sliced"],
      ["green pepper", 1, "", "sliced"],
      ["red onion", 1, "", "sliced"],
      ["ground cumin", 2, "tsp"],
      ["smoked paprika", 2, "tsp"],
      ["dried oregano", 1, "tsp"],
      ["lime", 1, ""],
      ["flour tortillas", 8, ""],
      ["vegetable oil", 2, "tbsp"],
      ["coriander", null, "handful"],
      ["avocado", 1, "", "sliced", true],
      ["salt", null, "to taste"],
    ],
    steps: [
      "Toss the chicken with the spices, salt and half the lime juice; leave ten minutes.",
      "Sear the chicken in batches over high heat until charred at the edges. Set aside.",
      "Cook the peppers and onion hard for six minutes so they blister but keep bite.",
      "Return the chicken, squeeze over the rest of the lime.",
      "Warm the tortillas directly over a flame for a few seconds a side.",
    ],
  },
  {
    title: "Thai Green Curry",
    description: "Fry the paste until it splits the coconut fat — that step makes the difference.",
    meal_types: ["dinner"],
    time_minutes: 35,
    servings: 4,
    i: [
      ["green curry paste", 3, "tbsp"],
      ["coconut milk", 800, "ml"],
      ["chicken thighs", 600, "g", "sliced"],
      ["green beans", 200, "g", "trimmed"],
      ["red pepper", 1, "", "sliced"],
      ["fish sauce", 2, "tbsp"],
      ["caster sugar", 1, "tsp"],
      ["lime", 1, ""],
      ["basil", null, "handful"],
      ["basmati rice", 300, "g"],
      ["vegetable oil", 1, "tbsp"],
    ],
    steps: [
      "Spoon the thick cream from the top of the coconut milk into a hot pan with the oil.",
      "Fry the paste in it for three minutes until it darkens and the oil separates.",
      "Add the chicken and coat, then pour in the rest of the coconut milk.",
      "Simmer twelve minutes, add the vegetables, and cook five more.",
      "Balance with fish sauce, sugar and lime — taste and adjust. Finish with basil.",
    ],
  },
  {
    title: "Mushroom Risotto",
    description: "Stir constantly, add stock a ladle at a time, and stop while it still flows.",
    meal_types: ["dinner"],
    time_minutes: 40,
    servings: 4,
    i: [
      ["arborio rice", 320, "g"],
      ["mushrooms", 400, "g", "sliced"],
      ["onion", 1, "", "very finely diced"],
      ["garlic", 2, "cloves", "minced"],
      ["white wine", 150, "ml"],
      ["vegetable stock", 1.2, "l", "kept hot"],
      ["parmesan", 80, "g", "grated"],
      ["butter", 50, "g"],
      ["olive oil", 2, "tbsp"],
      ["thyme", null, "few sprigs"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Brown the mushrooms hard in oil in batches, season, and set aside.",
      "Soften the onion in butter for eight minutes without colouring, then add garlic.",
      "Add the rice and toast two minutes until the edges turn translucent.",
      "Pour in the wine and stir until absorbed, then add hot stock a ladle at a time.",
      "After eighteen minutes the rice should be al dente. Beat in butter, parmesan and mushrooms off the heat.",
    ],
  },
  {
    title: "Roast Chicken with Vegetables",
    description: "The one to learn properly. Everything else is a variation on this.",
    meal_types: ["dinner"],
    time_minutes: 90,
    servings: 4,
    i: [
      ["whole chicken", 1.6, "kg"],
      ["potato", 800, "g", "quartered"],
      ["carrot", 4, "", "halved"],
      ["onion", 2, "", "quartered"],
      ["lemon", 1, "", "halved"],
      ["thyme", null, "few sprigs"],
      ["garlic", 1, "head", "halved"],
      ["butter", 50, "g", "softened"],
      ["olive oil", 3, "tbsp"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Salt the chicken generously an hour ahead and leave it uncovered in the fridge.",
      "Heat the oven to 220C. Rub the bird with butter, stuff the cavity with lemon and thyme.",
      "Toss the vegetables in oil in a roasting tin and sit the chicken on top.",
      "Roast 20 minutes, drop to 180C, and give it another 50 — juices should run clear.",
      "Rest at least fifteen minutes before carving. This is not optional.",
    ],
  },
  {
    title: "Beef Bourguignon",
    description: "A weekend dish. Brown the beef in small batches or you'll stew it grey.",
    meal_types: ["dinner"],
    time_minutes: 180,
    servings: 6,
    i: [
      ["beef chuck", 1.2, "kg", "cut into 4cm cubes"],
      ["streaky bacon", 150, "g", "diced"],
      ["onion", 2, "", "diced"],
      ["carrot", 3, "", "thickly sliced"],
      ["mushrooms", 300, "g", "halved"],
      ["garlic", 4, "cloves", "minced"],
      ["red wine", 750, "ml"],
      ["beef stock", 500, "ml"],
      ["tomato puree", 2, "tbsp"],
      ["plain flour", 3, "tbsp"],
      ["bay leaf", 2, ""],
      ["thyme", null, "few sprigs"],
      ["butter", 40, "g"],
      ["olive oil", 2, "tbsp"],
      ["salt", null, "to taste"],
      ["black pepper", null, "to taste"],
    ],
    steps: [
      "Dry the beef thoroughly and brown it in oil in small batches. Crowding is the classic mistake.",
      "Render the bacon, then soften the onion and carrot in the fat.",
      "Return the beef, dust with flour, and cook two minutes to lose the raw taste.",
      "Add tomato puree, wine, stock and herbs. Bring to a bare simmer.",
      "Cover and cook at 150C for two and a half hours, until it yields to a spoon.",
      "Brown the mushrooms separately in butter and fold them in for the last ten minutes.",
    ],
  },

  // -------------------------------------------------------------------- snack
  {
    title: "Hummus with Vegetable Sticks",
    description: "Ice water while blending is the trick to a properly light texture.",
    meal_types: ["snack", "lunch"],
    time_minutes: 10,
    servings: 4,
    i: [
      ["chickpeas", 400, "g", "drained"],
      ["tahini", 4, "tbsp"],
      ["lemon", 1, "", "juiced"],
      ["garlic", 1, "clove"],
      ["ground cumin", 0.5, "tsp"],
      ["olive oil", 3, "tbsp"],
      ["water", 4, "tbsp", "ice cold"],
      ["carrot", 2, "", "cut into sticks"],
      ["cucumber", 1, "", "cut into sticks"],
      ["salt", null, "to taste"],
    ],
    steps: [
      "Blend the tahini and lemon juice alone first, until pale and thick.",
      "Add chickpeas, garlic, cumin and salt, and blend to a paste.",
      "Trickle in ice water with the motor running until it turns light and glossy.",
      "Spread into a bowl, pool olive oil in the middle, serve with the vegetable sticks.",
    ],
  },
  {
    title: "Guacamole",
    description: "Mash it coarsely and salt it more than you think. Lime holds the colour.",
    meal_types: ["snack"],
    time_minutes: 10,
    servings: 4,
    i: [
      ["avocado", 3, "", "ripe"],
      ["lime", 1, "", "juiced"],
      ["red onion", 0.5, "", "finely diced"],
      ["red chilli", 1, "", "finely chopped"],
      ["coriander", null, "handful", "chopped"],
      ["tomato", 1, "", "deseeded and diced"],
      ["salt", null, "to taste"],
    ],
    steps: [
      "Mash the avocado roughly with a fork — texture is the point, not smoothness.",
      "Fold in the lime, onion, chilli and coriander.",
      "Add the tomato last so it doesn't turn everything watery.",
      "Salt, taste, and salt again. Under-seasoned guacamole is the usual failure.",
    ],
  },
  {
    title: "Spiced Popcorn",
    description: "Better than any bag, for the price of a handful of kernels.",
    meal_types: ["snack"],
    time_minutes: 8,
    servings: 2,
    i: [
      ["popcorn kernels", 80, "g"],
      ["vegetable oil", 2, "tbsp"],
      ["butter", 30, "g", "melted"],
      ["smoked paprika", 1, "tsp"],
      ["ground cumin", 0.5, "tsp"],
      ["salt", null, "to taste"],
    ],
    steps: [
      "Heat the oil with three kernels in a lidded pan until they pop.",
      "Add the rest, cover, and shake steadily until the pops slow to a few seconds apart.",
      "Tip into a large bowl straight away so the steam escapes and it stays crisp.",
      "Toss with melted butter, then the spices and salt.",
    ],
  },
  {
    title: "Toasted Seed Granola",
    description: "Press it flat and don't stir it, and you get clusters instead of dust.",
    meal_types: ["snack", "breakfast"],
    time_minutes: 35,
    servings: 10,
    i: [
      ["rolled oats", 300, "g"],
      ["almonds", 100, "g", "roughly chopped"],
      ["sunflower seeds", 60, "g"],
      ["pumpkin seeds", 60, "g"],
      ["desiccated coconut", 50, "g"],
      ["honey", 100, "g"],
      ["vegetable oil", 60, "ml"],
      ["ground cinnamon", 1, "tsp"],
      ["vanilla extract", 1, "tsp"],
      ["salt", 0.5, "tsp"],
    ],
    steps: [
      "Heat the oven to 150C — low and slow, or the honey burns before the oats colour.",
      "Warm the honey, oil, vanilla and cinnamon together until pourable.",
      "Toss through the dry ingredients until everything is evenly coated.",
      "Spread on a lined tray and press down firmly with the back of a spoon.",
      "Bake 30 minutes, rotating once but never stirring. Cool completely before breaking up.",
    ],
  },
  {
    title: "Rosemary Focaccia",
    description: "Mostly waiting. The dimpling and the pool of oil are what make it.",
    meal_types: ["snack", "lunch"],
    time_minutes: 150,
    servings: 8,
    i: [
      ["strong white flour", 500, "g"],
      ["fast-action yeast", 7, "g"],
      ["water", 400, "ml", "lukewarm"],
      ["olive oil", 80, "ml"],
      ["salt", 10, "g"],
      ["rosemary", null, "few sprigs", "leaves picked"],
      ["sea salt flakes", null, "to finish"],
    ],
    steps: [
      "Mix flour, yeast, salt and water to a very wet, shaggy dough. It should be too sticky to knead.",
      "Cover and leave 90 minutes, folding it over on itself every 30 if you remember.",
      "Pour half the oil into a tray, tip the dough in, and stretch it to the corners.",
      "Rest 30 minutes, then dimple hard with oiled fingers, right down to the base.",
      "Pour over the rest of the oil, scatter rosemary and salt flakes, and bake at 220C for 22 minutes.",
    ],
  },
  {
    title: "Peanut Butter Energy Balls",
    description: "No baking, and they keep a fortnight in the fridge.",
    meal_types: ["snack", "breakfast"],
    time_minutes: 15,
    servings: 12,
    i: [
      ["rolled oats", 150, "g"],
      ["peanut butter", 150, "g"],
      ["honey", 60, "g"],
      ["chia seeds", 2, "tbsp"],
      ["dark chocolate", 60, "g", "chopped"],
      ["desiccated coconut", 40, "g", null, true],
      ["vanilla extract", 1, "tsp"],
      ["salt", null, "pinch"],
    ],
    steps: [
      "Mix everything in a bowl — it should feel stiff and slightly sticky.",
      "If it crumbles add a spoon of honey; if it smears add more oats.",
      "Chill twenty minutes so it firms enough to handle.",
      "Roll into walnut-sized balls, optionally through coconut. Keep refrigerated.",
    ],
  },
];
